In [51]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
import math
from sklearn.model_selection import train_test_split

In [52]:
data = pd.read_csv('BuyComputer.csv')
data.drop(columns=['User ID',],axis=1,inplace=True)
data

,Age,EstimatedSalary,Purchased
0,19,19000,0
1,35,20000,0
2,26,43000,0
3,27,57000,0
4,19,76000,0
...,...,...,...
395,46,41000,1
396,51,23000,1
397,50,20000,1
398,36,33000,0


In [71]:
# Scaling data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
transformed_data = sc.fit_transform(data)

In [72]:
transformed_data

array([[-1.78179743, -1.49004624, -0.74593581],
       [-0.25358736, -1.46068138, -0.74593581],
       [-1.11320552, -0.78528968, -0.74593581],
       ...,
       [ 1.17910958, -1.46068138,  1.34059793],
       [-0.15807423, -1.07893824, -0.74593581],
       [ 1.08359645, -0.99084367,  1.34059793]])

In [73]:
# Splitting data

X = transformed_data[:,0:2]
Y = transformed_data[:,2]

Y = [0 if a<0 else 1 for a in Y]
Y = np.array(Y)


X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 36)

In [70]:
# define logistic_regression class

class LogisticRegression:
    
    def __init__(self,lr,epochs=100):
        self.learning_rate = lr
        self.epochs = epochs
        pass
    
    def fit(self,X,Y):
        # Assigning data to X and Y
        self.X = X
        self.Y = Y

        # Computing M -> No of training samples 
        # Computing N -> No of features
        self.Num_samples,self.Num_features = X.shape
        print(self.Num_samples,self.Num_features)

        # Initializing all the weights
        self.Weights = np.zeros(self.Num_features)
        self.Bias = 0
        for i in range(self.epochs):
            print("Epoch ",i)
            
            # Gradient Calculation
            ans = self.sigmoid(self.X)
            t = ( ans - self.Y.T )
            t = np.reshape( t, self.Num_samples ) 
            
            dW = np.dot( self.X.T, t ) / self.Num_samples
            db = np.sum( t ) / self.Num_samples
            
            self.Weights = self.Weights - self.learning_rate * dW    
            self.Bias = self.Bias - self.learning_rate * db
            
            print(self.get_loss())
        return self
    
    def sigmoid(self,X):
        return 1/(1+np.exp(-((X).dot(self.Weights)+self.Bias)))
    
    def get_loss(self):
        return (np.sum(-1*(self.Y)*np.log(self.sigmoid(self.X))-(1-self.Y)*np.log(1-self.sigmoid(self.X)))/self.Num_samples)
  
    # Return predictions based on X
    def predict(self,X):
        ret_val = []
        for dat in self.sigmoid(X):
            ret_val.append(1 if dat>=0.5 else 0)
        return ret_val

In [69]:
lr = LogisticRegression(0.1,400)
lr.fit(X_train,y_train)

320 2
Epoch  0
0.6801030360621636
Epoch  1
0.6677518677321456
Epoch  2
0.6560550871546823
Epoch  3
0.6449753891061054
Epoch  4
0.6344769138378068
Epoch  5
0.6245253621215798
Epoch  6
0.6150880689680652
Epoch  7
0.6061340420699095
Epoch  8
0.5976339708542312
Epoch  9
0.5895602116479672
Epoch  10
0.5818867539449392
Epoch  11
0.5745891721798436
Epoch  12
0.5676445668110672
Epoch  13
0.5610314979263731
Epoch  14
0.554729914036234
Epoch  15
0.5487210782225377
Epoch  16
0.5429874933719414
Epoch  17
0.5375128278446086
Epoch  18
0.5322818426081973
Epoch  19
0.5272803205994648
Epoch  20
0.5224949988562354
Epoch  21
0.5179135037848074
Epoch  22
0.5135242897862629
Epoch  23
0.5093165813540136
Epoch  24
0.5052803186691939
Epoch  25
0.5014061066556978
Epoch  26
0.4976851674088428
Epoch  27
0.4941092958774923
Epoch  28
0.49067081865618645
Epoch  29
0.4873625557290704
Epoch  30
0.4841777849992656
Epoch  31
0.4811102094342335
Epoch  32
0.47815392665838113
Epoch  33
0.4753034008276372
Epoch  34
0.47255

In [58]:
lr.Weights

array([2.07866605, 0.96539469])

In [59]:
def getScore(y_originals,y_pred):
    true = 0
    false = 0
    for i in range(len(y_pred)):
        if y_pred[i]==y_originals[i]:
            true = true + 1
        else:
            false = false + 1
    return true/(true+false)

In [74]:
# prediction on test data

y_pred = lr.predict(X_test)

In [61]:
# Accuracy
getScore(y_test,y_pred)*100

86.25

In [62]:
y_test

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [63]:
np.array(y_pred)

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [64]:
# Using sklearn LogisticRegression model

from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(random_state = 36)
LR.fit(X_train,y_train)


LogisticRegression(random_state=36)

In [75]:
y_pred = lr.predict(X_test)

In [66]:
getScore(y_test,y_pred)*100

86.25